### ISSUE TITLE
你这个不兼容正常requests代码？

### ISSUE THREAD

**Issue by ydf0509** [fishtn/hoopa#1]
如果已经用requests写好了的函数，这个不兼容，为什么非要学scrapy继承一个爬虫基类，然后模仿scrapy的钩子函数呢，想不通。。。

**Comment by nieweiming** [comment]
> 如果已经用requests写好了的函数，这个不兼容，为什么非要学scrapy继承一个爬虫基类，然后模仿scrapy的钩子函数呢，想不通。。。
方便切换，降低学习成本，不也挺好。
