### ISSUE TITLE
能不能基于我这个函数调度框架封装，

### ISSUE THREAD

**Issue by ydf0509** [fishtn/hoopa#2]
这个实现了分布式队列和并发，和确认消费。目前加上请求客户端就可以维护成一个爬虫框架，这个客户端是方便一键切换各种代理ip。不然的话，你目前这种封装方式的并发运行速度一定不如我，如果你不信的话，可以本机安装个nginx后面不代理接口。直接请求nginx80端口，我们对比下运行速度。

**Comment by fishtn** [comment]
谢谢你的issue，你的代码很优秀，我这样封装只是为了方便使用，使用场景不一样
